### ISSUE TITLE
Conformity van de data controleren

### ISSUE THREAD

**Issue by Rachelledezwart** [fyermen8/Pyta#12]
Controleer de data op de volgende aspecten:

**Allowed character checks**
Checks to ascertain that only expected characters are present in a field. For example a numeric field may only allow the digits 0–9, the decimal point and perhaps a minus sign or commas. A text field such as a personal name might disallow characters such a markup-based security attack. An e-mail address might require at least one @ sign and various other structural details. Regular expressions are effective ways of implementing such checks.

**Batch totals**
Checks for missing records. Numerical fields may be added together for all records in a batch. The batch total is entered and the computer checks that the total is correct, e.g., add the 'Total Cost' field of a number of transactions together.

**Consistency checks**
Checks fields to ensure data in these fields corresponds, e.g., If Title = "Mr.", then Gender = "M".

**Format or picture check**
Checks that the data is in a specified format (template), e.g., dates have to be in the format DD/MM/YYYY. Regular expressions should be considered for this type of validation.

**Presence check**
Checks that important data is actually present and have not been missed out, e.g., customers may be required to have their telephone numbers listed.

**Comment by LeCanard272** [comment]
nvt. epic sluiten
